### ISSUE TITLE
Complex multiplication is incorrectly handling edge cases

### ISSUE THREAD

**Issue by t4c1** [argonne-lcf/SyclCPLX#15]
For example with:
z = DBL_MAX + 1i
w = DBL_MAX + NaNi
expected: z * w = NaN + NaNi
by implementation in this repo: z * w = INF + INFi

**Comment by TApplencourt** [comment]
I can reproduce with `dpcpp`:
```
tapplencourt@iris18:~/tmp/SyclCPLX> cat max_nan_bug.cpp
#include <sycl/sycl.hpp>
#include "sycl_ext_complex.hpp"
#include <complex>
#include <cassert>
#include <cfloat>

int main() {

  sycl::queue Q(sycl::gpu_selector{});
  std::cout << "Running on "
            << Q.get_device().get_info<sycl::info::device::name>()
            << "\n";

  sycl::ext::cplx::complex<double> w{DBL_MAX, std::nan("")};

  auto* gpu_result = sycl::malloc_shared<sycl::ext::cplx::complex<double>>(1,Q);
  Q.single_task([=]() {
    sycl::ext::cplx::complex<double> z{DBL_MAX, 1};
    gpu_result[0] = z*w;
  }).wait();

  std::cout << "gpu_result " << gpu_result[0] << std::endl;
  assert(std::isnan(gpu_result[0].real()));
  assert(std::isnan(gpu_result[0].imag()));
  return 0;
}
tapplencourt@iris18:~/tmp/SyclCPLX> dpcpp -fp-model=precise -I include/ max_nan_bug.cpp
tapplencourt@iris18:~/tmp/SyclCPLX> ./a.out
Running on Intel(R) Iris(R) Pro Graphics P580 [0x193a]
gpu_result (inf,inf)
a.out: max_nan_bug.cpp:23: int main(): Assertion `std::isnan(gpu_result[0].real())' failed.
Aborted
```

**Comment by TApplencourt** [comment]
@t4c1 IEEE 754-2008 is not my strong point, do you have some reference implementation / test-suite that I can use to check the correctness of our implementation?

Our implementation behaves the same as clang++ does (https://github.com/llvm/llvm-project/blob/385cc25a531a72c393cee44689e2c3194615bcec/libcxx/include/complex#L587).  I'm a little afraid of modifying the code with my current limited understanding of EEE 754.

**Comment by TApplencourt** [comment]
gcc seem to agree with us (and clang++):
```
$cat complex.c
#include <complex.h>
#include <stdio.h>
#include <float.h>
#include <math.h>

int main(void)
{
    double complex z1 = DBL_MAX + I;
    double complex z2 = CMPLX(DBL_MAX,NAN);
    double complex z3 = z1 * z2;
    printf("(%.1e,%.1f) * (%.1e,%.1f) = (%.1f,%.1f)\n",
        creal(z1), cimag(z1),
        creal(z2), cimag(z2),
        creal(z3), cimag(z3) );
}
$gcc complex.c
$./a.out
(1.8e+308,1.0) * (1.8e+308,nan) = (inf,inf)

**Comment by t4c1** [comment]
You are right - this is equivalent to that example implementation and correct according to the spec. The spec does not define the behavior in presence of either NaN inputs or overflow, both of which are present in my example (it even comments below that example implementation that it is not ideal as it does not cover overflow).

**Comment by TApplencourt** [comment]
Agree! But Thanks a lot for raising this issue; this allowed me to learn new things about complex in C/C++ :).
