### ISSUE TITLE
document use of oneMKL and other std::complex APIs taking pointers

### ISSUE THREAD

**Issue by bd4** [argonne-lcf/SyclCPLX#19]
The gtensor diff to get this working, at least as far as passing CI and unit tests, is almost trivial:

https://github.com/wdmapp/gtensor/compare/main...bd4:gtensor:pr/sycl-ext-complex

I made one change to `sycl_ext_complex.hpp`, to include the gtensor version compat header instead of `sycl/sycl.hpp`, so it will past CI on public oneAPI (still uses `CL/sycl.hpp`). Otherwise unchanged from upstream.

The major roadblock to merging this into the main gtensor branch, is lack of MKL support. Is there any temporary workaround for this, while we wait for a release that supports it? I imagine there are some semi evil but maybe acceptable tricks we could use.

**Comment by TApplencourt** [comment]
I was thinking we enable some implicit cast between sycl::complex and std::complex. Like in the hello world, we call a function who takes some `std::complex<double> x`  with a `sycl::ext::cplx::complex<double>` at it works out of the box. 

So I'm not sure I understand why oneMKL doesn't work.

**Comment by bd4** [comment]
The problem, as I understand it, is that implicit conversion only works in when passing by value and not using templates. It tends to break down in other cases:

- passing pointers (c++ has no way of knowing the data layout is identical, so this makes sense)
- passing references (don't understand why)
- templating on component type (not sure about this either)

For oneMKL USM interfaces, it fails because the arrays are passed as pointer to complex.

**Comment by bd4** [comment]
Here are some examples of what doesn't work: https://github.com/argonne-lcf/SyclCPLX/compare/main...bd4:SyclCPLX:conversion-challenges

**Comment by bd4** [comment]
Lets close after merging a documentation update, I think the correct solution here. As a start, we could just link to the gtensor commit.

**Comment by bd4** [comment]
See pr #24

**Comment by TApplencourt** [comment]
This is perfect; thanks a lot!
