### ISSUE TITLE
CI clang-format

### ISSUE THREAD

**Issue by jle-quel** [argonne-lcf/SyclCPLX#34]
Is there a reason for having multiple steps in the CI for formatting?

The steps use two different versions of `clang-format` (9 and 14).
Having multiple version running create CI errors which can't be solved if a source file contains code that was considered "legal" in version 9 but "illegal" in version 14.

Please take a look at this PR https://github.com/argonne-lcf/SyclCPLX/pull/33 with the two last commits to get a better idea.

Could we keep only one formatting step, with the latest clang-format version?

**Comment by bd4** [comment]
Sorry I missed this, we now have only 14 enabled. Unfortunately figuring out how to adjust .clang-format config so it's stable across versions is difficult. Should be fixed now.
